//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILG.Codex.CodexR4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILG.Codex.CodexR4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About3 {
            get {
                object obj = ResourceManager.GetObject("About3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_database_16x16 {
            get {
                object obj = ResourceManager.GetObject("add-database_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app_16x16 {
            get {
                object obj = ResourceManager.GetObject("app_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app_32x32 {
            get {
                object obj = ResourceManager.GetObject("app_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_left_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_right_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attach_next_16 {
            get {
                object obj = ResourceManager.GetObject("attach_next_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16 {
            get {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///USE [Codex2007DS]
        ///
        ///IF OBJECT_ID(N&apos;CodexDS_DDOCS_History&apos;, N&apos;U&apos;) IS NULL 
        ///BEGIN
        ///	SET ANSI_NULLS ON
        ///
        ///	SET QUOTED_IDENTIFIER ON
        ///
        ///	CREATE TABLE [dbo].[CodexDS_DDOCS_History](
        ///		[id] [int] IDENTITY(0,1) NOT NULL,
        ///		[H_Date] [datetime] NOT NULL,
        ///		[H_Caption] [nvarchar](1024) NOT NULL,
        ///		[H_Title] [nvarchar](1024) NOT NULL,
        ///		[H_Status] [int] NOT NULL,
        ///		[H_OperationStatus] [int] NOT NULL,
        ///		[H_TimeStamp] [timestamp] NOT NULL,
        ///		[H_ByUser] [nvarchar](1024) NOT NULL,
        ///		[C_ID] [int] NOT NULL,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateHistoryTable {
            get {
                return ResourceManager.GetString("CreateHistoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_database_16x16 {
            get {
                object obj = ResourceManager.GetObject("delete-database_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_green {
            get {
                object obj = ResourceManager.GetObject("disk_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diskette_16 {
            get {
                object obj = ResourceManager.GetObject("diskette_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorLeft4 {
            get {
                object obj = ResourceManager.GetObject("ErrorLeft4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex DS Scripts
        ///-- Full Text from all Database
        ///-- Version 1.0 
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 
        ///-- V 2017 October 5
        ///
        ///
        ///
        ///DECLARE @IsFullTextInstalled int
        ///SET @IsFullTextInstalled = (SELECT FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///
        ///IF (@IsFullTextInstalled &lt;&gt; 1)
        ///BEGIN
        /// RAISERROR (&apos;Full Text is not installed on SQL Server&apos;,0,0);
        ///END
        ///
        ///USE [Codex2007DS]
        ///if (select DATABASEPROPERTY(DB_NAME(), N&apos;IsFullTextEnabled&apos;)) &lt;&gt; 1 
        ///exec sp_fulltext_database N&apos;enable&apos; 
        ///	
        ///if ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullTextCreate {
            get {
                return ResourceManager.GetString("FullTextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex DS Scripts
        ///-- Full Text from all Database
        ///-- Version 1.0 RC
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 
        ///-- V 2017 October 5
        ///
        ///
        ///
        ///DECLARE @IsFullTextInstalled int
        ///SET @IsFullTextInstalled = (SELECT FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///
        ///IF (@IsFullTextInstalled &lt;&gt; 1)
        ///BEGIN
        /// RAISERROR (&apos;Full Text is not installed on SQL Server&apos;,0,0);
        ///END
        ///
        ///USE [Codex2007DS]
        ///if (select DATABASEPROPERTY(DB_NAME(), N&apos;IsFullTextEnabled&apos;)) &lt;&gt; 1 
        ///exec sp_fulltext_database N&apos;enable&apos; 
        ///	
        ///if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullTextCreateAndPopulate_DS {
            get {
                return ResourceManager.GetString("FullTextCreateAndPopulate_DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex DS Scripts
        ///-- Full Text from all Database
        ///-- Version 1.0 
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 
        ///-- V 2017 October 5
        ///
        ///
        ///
        ///
        ///USE [Codex2007DS]
        ///
        ///
        ///-- POPULATE FULL TEXT
        ///
        ///EXEC sp_fulltext_table CodexDS_DDOCS, &apos;Start_change_tracking&apos;
        ///EXEC sp_fulltext_table CodexDS_DDOCS, &apos;Start_background_updateindex&apos;
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string FullTextPopulate {
            get {
                return ResourceManager.GetString("FullTextPopulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_32x32 {
            get {
                object obj = ResourceManager.GetObject("help_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help2 {
            get {
                object obj = ResourceManager.GetObject("help2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Left1 {
            get {
                object obj = ResourceManager.GetObject("Left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not exists (select * from master.dbo.syslogins where loginname = N&apos;BUILTIN\Users&apos;)
        ///	exec sp_grantlogin N&apos;BUILTIN\Users&apos;
        ///	exec sp_defaultdb N&apos;BUILTIN\Users&apos;, N&apos;master&apos;
        ///	exec sp_defaultlanguage N&apos;BUILTIN\Users&apos;, N&apos;us_english&apos;
        ///GO
        ///
        ///exec sp_addsrvrolemember N&apos;BUILTIN\Users&apos;, sysadmin
        ///GO
        ///
        ///if not exists (select * from dbo.sysusers where name = N&apos;BUILTIN\Users&apos; and uid &lt; 16382)
        ///	EXEC sp_grantdbaccess N&apos;BUILTIN\Users&apos;, N&apos;BUILTIN\Users&apos;
        ///GO
        ///
        ///USE master
        ///exec sp_addrolemember N&apos;db_owner&apos;, N&apos;BUILTIN\User [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_BuiltinUsersDS {
            get {
                return ResourceManager.GetString("Legacy_BuiltinUsersDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare  @builtin_users as nvarchar(128)
        ///set @builtin_users = suser_sname(0x01020000000000052000000021020000)
        ///
        ///
        ///if not exists (select * from master.dbo.syslogins where loginname = @builtin_users)
        ///	exec sp_grantlogin @builtin_users
        ///	exec sp_defaultdb  @builtin_users, N&apos;master&apos;
        ///	exec sp_defaultlanguage @builtin_users, N&apos;us_english&apos;
        ///
        ///GO
        ///
        ///declare   @builtin_users as nvarchar(128)
        ///set @builtin_users = suser_sname(0x01020000000000052000000021020000)
        ///
        ///exec sp_addsrvrolemember @builtin_users, sysadmin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_BuiltinUsersDSR3 {
            get {
                return ResourceManager.GetString("Legacy_BuiltinUsersDSR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail_16 {
            get {
                object obj = ResourceManager.GetObject("mail_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_16 {
            get {
                object obj = ResourceManager.GetObject("play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_161 {
            get {
                object obj = ResourceManager.GetObject("play_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_disk_16x16 {
            get {
                object obj = ResourceManager.GetObject("play-disk_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex DS Scripts
        ///-- Drop CodexUsers from all Database
        ///-- Version 2.0
        ///-- (C) Copyright By Gergian Microsystems 2005-2016 DS 1.5
        ///
        ///
        ///--Codex2007DS
        ///-- ***************************************************************************************************
        ///USE [Codex2007DS]
        ///
        ///if exists (select * from sys.schemas where name = N&apos;CodexDSUser&apos;)
        ///	DROP SCHEMA  CodexDSUser
        ///
        ///
        ///USE [Codex2007DS]
        ///
        ///if exists (select * from dbo.sysusers where name = N&apos;CodexDSUser&apos; and uid &lt; 16382)
        ///	DROP USER CodexDSUser
        ///
        ///
        ///
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Drop_DSCU {
            get {
                return ResourceManager.GetString("Script_Drop_DSCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex DS Scripts
        ///-- Drop CodexUsers from all Database
        ///-- Version 2.0
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 DS 1.5
        ///
        ///
        ///--Codex2007DS
        ///-- ***************************************************************************************************
        ///USE [Codex2007DS]
        ///
        ///if exists (select * from sys.schemas where name = N&apos;CodexDSXUser&apos;)
        ///	DROP SCHEMA  CodexDSXUser
        ///
        ///
        ///USE [Codex2007DS]
        ///
        ///if exists (select * from dbo.sysusers where name = N&apos;CodexDSXUser&apos; and uid &lt; 16382)
        ///	DROP USER CodexDSXUser
        ///
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Drop_DSCXU {
            get {
                return ResourceManager.GetString("Script_Drop_DSCXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex R4 Scripts
        ///-- Registeer Codex Users from all Database
        ///-- Version 2.1
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 DS 1.5
        ///
        ///
        ///-- Codex DS 
        ///-- ************************************************************************************************************************
        ///
        ///USE[Codex2007DS]
        ///
        ///declare @logindb nvarchar(132), @loginlang nvarchar(132)
        ///
        ///if not exists (select * from master.dbo.syslogins where loginname = N&apos;CodexDSUser&apos;)
        ///BEGIN
        ///    select @logindb = N&apos;Codex2007DS&apos;, @loginlang = null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Register_DSCU {
            get {
                return ResourceManager.GetString("Script_Register_DSCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Codex R4 Scripts
        ///-- Registeer Codex Users from all Database
        ///-- Version 2.1
        ///-- (C) Copyright By Gergian Microsystems 2005-2017 DS 1.5
        ///
        ///
        ///-- Codex DS 
        ///-- ************************************************************************************************************************
        ///
        ///USE[Codex2007DS]
        ///
        ///declare @logindb nvarchar(132), @loginlang nvarchar(132)
        ///
        ///if not exists (select * from master.dbo.syslogins where loginname = N&apos;CodexDSXUser&apos;)
        ///BEGIN
        ///    select @logindb = N&apos;Codex2007DS&apos;, @loginlang = nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Register_DSCXU {
            get {
                return ResourceManager.GetString("Script_Register_DSCXU", resourceCulture);
            }
        }
    }
}
