//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILG.Codex.CodexR4.CodexSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class DirectoryConfigurations : global::System.Configuration.ApplicationSettingsBase {
        
        private static DirectoryConfigurations defaultInstance = ((DirectoryConfigurations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DirectoryConfigurations())));
        
        public static DirectoryConfigurations Default {
            get {
                return defaultInstance;
            }
        }
    }
}
